---
name: Schedule - Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: false
        required: false
        type: boolean
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/renovate/**.json"
      - ".github/renovate/**.json5"
      - ".github/workflows/schedule-renovate.yaml"

jobs:
  renovate:
    name: Renovate
    uses: renovatebot/github-action@v36.0.0
    with:
      configurationFile: ".github/renovate.json5"
      dryRun: ${{ inputs.dryRun || 'false' }}
      renovateLogLevel: ${{ inputs.logLevel || 'debug' }}
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
