---
name: Schedule - Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: false
        required: false
        type: boolean
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/renovate/**.json"
      - ".github/renovate/**.json5"
      - ".github/workflows/schedule-renovate.yaml"

